CONTIKI_PROJECT = hello-world 
all: $(CONTIKI_PROJECT)


#UIP_CONF_IPV6=1
APPS = serial-shell powertrace collect-view
CONTIKI = ../..
include $(CONTIKI)/Makefile.include
-include /home/user/nes/testbed-scripts/Makefile.include