CONTIKI_PROJECT = empty 
all: $(CONTIKI_PROJECT)

UIP_CONF_IPV6=1
APPS = shell-serial powertrace collect-view shell
CONTIKI = ../..
include $(CONTIKI)/Makefile.include
-include /home/user/nes/testbed-scripts/Makefile.include